### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JNU-luyi** [gabrielbianchin/TEMPROT#1]
1,Do you have any specific environment configuration
2，Which data is it?
![image](https://github.com/gabrielbianchin/TEMPROT/assets/100257990/732b15c4-2582-482e-9b02-5a4240be7ad6)
3，

**Comment by gabrielbianchin** [comment]
Hi @JNU-luyi , about our questions:
1 - I ran the code in different environments, so different versions of the libraries were used (e.g. numpy and pandas). If you want, I can post the configuration of the most used environment in my experiments.
2 - The dataset was built based on data-cafa.tar.gz file. We removed duplicated proteins from different sets. You can find the dataset employed in our work [here](https://zenodo.org/record/7409660)

**Comment by JNU-luyi** [comment]
Of course, thank you! Could you please share these several files with me?（'train_data_train.pkl'，train_data_valid.pkl，test_data.pkl，terms.pkl） 
I am a beginner, and I would like to learn about the data generation process. 
train = pd.read_pickle('train_data_train.pkl')
valid = pd.read_pickle('train_data_valid.pkl')
test = pd.read_pickle('test_data.pkl')
terms = pd.read_pickle('terms.pkl')

**Comment by gabrielbianchin** [comment]
You can find these files [here](https://drive.google.com/drive/folders/1aG2W7KVjoQD6K_YlEqNiaO-4VvwnEbJs)
