### ISSUE TITLE
Inquiry Regarding Paper Code

### ISSUE THREAD

**Issue by JNU-luyi** [gabrielbianchin/TEMPROT#2]
I hope this message finds you well. I am currently in the process of reading your paper, and I have come across a section where you have provided data. I am particularly interested in understanding the source of the data you used, specifically related to DeepGOPlus.

In your paper's 'dataset.py,' I observed the following code:

```python
train = pd.read_pickle('train_data_train.pkl')
valid = pd.read_pickle('train_data_valid.pkl')
test = pd.read_pickle('test_data.pkl')
terms = pd.read_pickle('terms.pkl')
Based on this code snippet, I presume that the data used in your research might have been generated from these files. However, I have been unable to locate these specific files on the official DeepGOPlus website or documentation.

I would greatly appreciate it if you could kindly provide some insights into the origin of this data or clarify how it was obtained. Understanding the source of the data would greatly assist me in my own research endeavors.

Thank you very much for your time and assistance in this matter. I look forward to your response.

**Comment by JNU-luyi** [comment]
![image](https://github.com/gabrielbianchin/TEMPROT/assets/100257990/2bf6787d-f26c-41d9-ad78-316eeabf4fe5)
This code loads files from a bunch of data, but I don't know which one. In the DeepGoPlus website, it seems that many folders have 'train_data.pkl' and 'test_data.pkl'. It looks like you also did some splitting for the training data. Would it be possible for you to provide the four data files loaded in the following code? Thank you very much.
train = pd.read_pickle('train_data_train.pkl')
valid = pd.read_pickle('train_data_valid.pkl')
test = pd.read_pickle('test_data.pkl')
terms = pd.read_pickle('terms.pkl')

**Comment by gabrielbianchin** [comment]
Hi @JNU-luyi .

We have used data-cafa.tar.gz. In this folder, the authors of DeepGOPlus provided the training and validation sets from train_data.pkl file

**Comment by JNU-luyi** [comment]
ok thanks
