### ISSUE TITLE
blast 

### ISSUE THREAD

**Issue by JNU-luyi** [gabrielbianchin/TEMPROT#3]
Hello! Could you please explain how the BLAST alignment is performed in the code? Could you specify which tool is used for the alignment and which file sequences are being aligned? Lastly, how is the file 'bp-blast.npy' generated from this process?

**Comment by gabrielbianchin** [comment]
Hi @JNU-luyi , thanks for your comment. I have added the file blast.py to run BLAST and generate predictions. 

You should install BLAST if you don't have it in your environment. You can run
`sudo apt install ncbi-blast+`
